bug-WDP180901-1
mateuszwrobel/wdp-1809-01 pull request #14
Opened 2018-10-05 19:13 UTC by NatalGi

Dodano brakujące zdjęcia na kartach produktów oraz w "ostatnie na blogu".

2018-10-08 18:25 UTC, annakowalczuk approved these changes

2018-10-11 22:37 UTC, stepek requested changes

2018-10-11 22:37 UTC, stepek commented on src/sass/components/_product-box.scss
> +
Proszę usuń te niepotrzebne spacje

2018-10-14 20:48 UTC, annakowalczuk approved these changes

2018-10-15 06:22 UTC, stepek approved these changes

2018-10-15 15:52 UTC, merged