task-WDP180901-23
mateuszwrobel/wdp-1809-01 pull request #18
Opened 2018-10-08 18:23 UTC by NatalGi

Według wytycznych należało dodać **sekcję "promowane"** (tylko HTML + CSS, implementacja RWD do tej sekcji jest częścią innego taska).

**1. Karta produktu po lewej:**
- Kropki obok nagłówka "Hot deals" mają być pomarańczowe na hover oraz gdy dany slajd jest aktywny (oskryptowanie slidera będzie częścią innego taska, tutaj należy tylko przewidzieć w CSS aktywny stan dla danej kropki).
- Button "Add to cart" oraz licznik (statyczny, animację klient stworzy we własnym zakresie) mają pojawiać się na hover zdjęcia produktu.
- Trzy przyciski po lewej stronie od ceny mają mieć taki sam efekt hover, jak inne elementy tego typu na stronie.

**2. Wyróżniony produkt po prawej:**
- Półprzezroczysty pasek z tytułem i button "Shop now" mają być zawsze widoczne.
- Buttony ze strzałkami w prawo i w lewo pod zdjęciem mają stawać się pomarańczowe na hover.

Stworzono sekcję wg wytycznych.

2018-10-09 21:44 UTC, annakowalczuk requested changes
Wygląda dobrze, jedynie kółka z licznikiem są za nisko. I napis add to cart nie pojawia się równocześnie z licznikiem (ale to chyba w innym tasku rozwiązujesz).

2018-10-10 16:42 UTC, NatalGi commented
Dodałam margines dolny do "kółek z licznikiem", co do drugiej kwestii jednolite animacje na hover ustawiłam w branchu bug-WDP180901-9, który nie jest jeszcze zmergowany z masterem. Na ten moment dodałam odpowiedni kod w komentarzu (plik src/sass/components/_hot-deals.scss linia 14).

2018-10-13 08:29 UTC, annakowalczuk approved these changes

2018-10-15 06:23 UTC, stepek approved these changes

2018-10-15 15:54 UTC, merged